### ISSUE TITLE
Cannot resolve shadow components when jsx extension is used

### ISSUE THREAD

**Issue by loremipson** [ChristopherBiscardi/gatsby-theme-examples#21] opened 2019-02-15 16:17 UTC
Naming shadow components as `FileName.js` works, but `FileName.jsx` fails:

`Error: Cannot find module '/path/from/dirname/Filename'`

**Comment by ChristopherBiscardi** [comment] 2019-02-17 23:21
yeah, looks like a bug. Reproduced in https://github.com/ChristopherBiscardi/gatsby-theme-examples/tree/jsx-extension-bug

**Comment by ChristopherBiscardi** [comment] 2019-02-18 00:35
I have a fix for this locally, just need to test it a bit more

**Closed as completed** 2019-02-19 22:49 UTC
Labels: bug
